# Generated by Django 2.2.11 on 2020-05-04 05:20

from django.db import migrations
# from teachers.models import Teacher


def forwards(apps, shema_editor):
    Teacher = apps.get_model('teachers', 'Teacher')
    for teacher in Teacher.objects.exclude(phone='').iterator():
        # 1
        # phone = ''
        # for char in student.phone:
        #     if char.isdigit():
        #         phone += char
        ##########################
        # phone = ''.join([char for char in student.phone if char.isdigit()])
        phone = ''.join(char for char in teacher.phone if char.isdigit())
        # phone = ''.join(filter(lambda x: x.isdigit(), student.phone))
        teacher.phone = phone
        teacher.save()


def backwards(apps, shema_editor):
    print('backwards' * 15)

class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_auto_20200426_2214'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
