# Generated by Django 2.2.11 on 2020-05-05 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0007_auto_20200505_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logger',
            name='method',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='logger',
            name='path',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='logger',
            name='time_delta',
            field=models.CharField(max_length=128),
        ),
    ]
