# Generated by Django 2.2.11 on 2020-05-05 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0008_auto_20200505_2242'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Logger',
            new_name='Loger',
        ),
    ]
