# Generated by Django 2.2.11 on 2020-05-05 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0009_auto_20200505_2329'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Loger',
            new_name='Logger',
        ),
    ]
