# Generated by Django 2.2.11 on 2020-04-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=128)),
                ('head', models.CharField(max_length=128)),
                ('phone', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
